config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index', to: 'dashboard#index', as: :dashboard_index
  get 'dashboard/normal', to: 'dashboard#normal', as: :dashboard_normal
  get 'get/project', to: 'projects#select', as: :selection_project

  post 'projects/create_repos' => 'projects#create_repos'

  get 'repository/index', to: 'repository#index', as: :repository_index
  get 'repository/branch', to: 'repository#branch', as: :repository_branch

  root to: 'dashboard#index'
  resources :languages
  resources :task_requirements
  resources :user_tasks
  resources :user_abilities
  resources :user_languages

  # Rotas devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved
  scope "/administrador" do
    resources :users
  end

  resources :projects do
    resources :function_user_projects
    resources :releases
    resources :sprints do
      resources :user_stories do # Recurso carregado duas vezes para facilitar no controler
        resources :tasks
      end
    end

    resources :themes do
      resources :user_stories do
        resources :user_story_acceptance_criterions
      end
    end
  end

  resources :locals
  resources :functions
  resources :abilities
end

app/models/ability.rb
class Ability < ApplicationRecord

  def self.available
    Ability.all
  end
  # Relacionamentos
  belongs_to :project, foreign_key: "scope",class_name: 'Project'
end

app/models/function.rb
class Function < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  def self.available_for_user user
    Language.all - user.languages 
  end
end

app/models/local.rb
class Local < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  def percentage_completed
    # Calculo ainda será implmentado
    rand(1...100)
  end

  # Projetos em aberto
  def self.available
    Project.all
  end

  # Relacionamentos
  has_many :function_user_projects
  has_many :users, through: :function_user_projects
  has_many :functions, through: :function_user_projects
  belongs_to :local
end

app/models/release.rb
class Release < ApplicationRecord

  def self.from_project project
    Release.where project: project
  end
  
  # Relacionamentos
  belongs_to :project
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :project
  belongs_to :release
end

app/models/task.rb
class Task < ApplicationRecord

  # Relacionamentos
  belongs_to :sprint
  belongs_to :user_story
end

app/models/theme.rb
class Theme < ApplicationRecord
  # Relacionamentos
  belongs_to :project
  has_many :user_stories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Foto
  mount_uploader :avatar, AvatarUploader

  # Permissão de acesso ao sistema apenas quando administrador validar
  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  # Relacionamentos
  belongs_to :local
  has_many :user_languages
  has_many :languages, through: :user_languages
  has_many :function_user_projects
  has_many :projects, through: :function_user_projects
  has_many :functions, through: :function_user_projects

  accepts_nested_attributes_for :local, reject_if: :all_blank, allow_destroy: true
end

app/models/user_ability.rb
class UserAbility < ApplicationRecord
  belongs_to :user
  belongs_to :ability
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :user
end

app/models/user_story.rb
class UserStory < ApplicationRecord

  # Relacionamentos
  has_many :user_story_acceptance_criterions
  belongs_to :theme
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :set_user_story, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  before_action :set_theme

  # GET /user_stories
  # GET /user_stories.json
  def index
    @user_stories = UserStory.all
  end

  # GET /user_stories/1
  # GET /user_stories/1.json
  def show
    @user_story_acceptance_criterions = @user_story.user_story_acceptance_criterions
  end

  # GET /user_stories/new
  def new
    @user_story = UserStory.new
  end

  # GET /user_stories/1/edit
  def edit
  end

  # POST /user_stories
  # POST /user_stories.json
  def create
    @user_story = UserStory.new(user_story_params)
    @user_story.theme = @theme

    respond_to do |format|
      if @user_story.save
        format.html { redirect_to [@project, @theme], notice: 'User story criada com sucesso.' }
        format.json { render :show, status: :created, location: @user_story }
      else
        format.html { render :new }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stories/1
  # PATCH/PUT /user_stories/1.json
  def update
    respond_to do |format|
      if @user_story.update(user_story_params)
        format.html { redirect_to [@project, @theme, @user_story], notice: 'User story atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @user_story }
      else
        format.html { render :edit }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stories/1
  # DELETE /user_stories/1.json
  def destroy
    @user_story.destroy
    respond_to do |format|
      format.html { redirect_to [@project, @theme], notice: 'User story deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_story
      @user_story = UserStory.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_theme
      @theme = Theme.find(params[:theme_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_story_params
      params.require(:user_story).permit(:description, :business_value, :status, :story_points, :theme_id)
    end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_stories/_form.html.erb
<div class="ui form">
  <h4 class="ui dividing header">Informações</h4>
  <%= form_for([@project, @theme, user_story]) do |f| %>
    <% if user_story.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user_story.errors.count, "error") %> prohibited this user_story from being saved:</h2>
        <ul>
        <% user_story.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label :business_value, id: 'label_business_value' %>
        <%= f.range_field :business_value, :in => 0..10000 %>
      </div>

      <div class="field">
        <%= f.label :status %>
        <%= f.number_field :status %>
      </div>

      <div class="field">
        <%= f.label :story_points, id: 'label_story_points' %>
        <%= f.range_field :story_points, :in => 0..1000 %>
      </div>

      <div class="actions">
      <%= f.submit class:'ui teal button' %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(".form").change(function() {
    story_points = $("#user_story_story_points").val();
    label = $("#label_story_points");
    label.text("Pontos de relator: " + story_points);

    business_value = $("#user_story_business_value").val();
    label = $("#label_business_value");
    label.text("Valor de negócio: " + business_value);
  })
</script>

app/views/user_stories/_index.html.erb
<h1 class="ui header" ><%= "Tema: #{@theme.name} " %>
  <br>
  <hr>
  User Stories
</h1>

<table class='ui orange table'>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Valor de negócio</th>
      <th>Status</th>
      <th>Story points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stories.each do |user_story| %>
      <tr>
        <td><%= user_story.description %></td>
        <td><%= user_story.business_value %></td>
        <td><%= user_story.status %></td>
        <td><%= user_story.story_points %></td>
        <td><%= link_to 'Detalhes', project_theme_user_story_path(@project, @theme, user_story), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Editar', edit_project_theme_user_story_path(@project, @theme, user_story), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Excluir', [@project, @theme, user_story], method: :delete, data: { confirm: 'Você tem certeza disso?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova User Story', new_project_theme_user_story_path(@project,@theme), class: 'ui teal button' %>
<%= link_to 'Voltar', [@project,@theme], class: 'ui button' %>

app/views/user_stories/edit.html.erb
<h1>Editar User Story</h1>

<%= render 'form', user_story: @user_story %>

<%= link_to 'Detalhes', [@project, @theme, @user_story], class: 'ui button' %>
<%= link_to 'Voltar', project_theme_user_stories_path(@project, @theme), class: 'ui button' %>

app/views/user_stories/index.html.erb
<%= render 'index' %>

app/views/user_stories/new.html.erb
<h1>Novo User Story</h1>

<%= render 'form', user_story: @user_story %>

<%= link_to 'Voltar', project_theme_user_stories_path(@project, @theme), class: 'ui button' %>

app/views/user_stories/show.html.erb
<div class='ui padded center aligned teal segment show'>
    <p>
    <strong>Descrição:</strong>
    <%= @user_story.description %>
  </p>

    <p>
    <strong>Valor de negócio:</strong>
    <%= @user_story.business_value %>
  </p>

    <p>
    <strong>Status:</strong>
    <%= @user_story.status %>
  </p>

    <p>
    <strong>Story points:</strong>
    <%= @user_story.story_points %>
  </p>

  <%= link_to 'Editar', edit_project_theme_user_story_path(@project, @theme, @user_story), class: 'ui button' %>
  <%= link_to 'Voltar', [@project, @theme], class: 'ui button' %>
</div>

<%= render 'user_story_acceptance_criterions/index' %>