config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index', to: 'dashboard#index', as: :dashboard_index
  get 'dashboard/normal', to: 'dashboard#normal', as: :dashboard_normal
  get 'get/project', to: 'projects#select', as: :selection_project

  post 'projects/create_repos' => 'projects#create_repos'

  get 'repository/index', to: 'repository#index', as: :repository_index
  get 'repository/branch', to: 'repository#branch', as: :repository_branch

  root to: 'dashboard#index'
  resources :languages
  resources :task_requirements
  resources :user_tasks
  resources :user_abilities
  resources :user_languages

  # Rotas devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved
  scope "/administrador" do
    resources :users
  end

  resources :projects do
    resources :function_user_projects
    resources :releases
    resources :sprints do
      resources :user_stories do # Recurso carregado duas vezes para facilitar no controler
        resources :tasks
      end
    end

    resources :themes do
      resources :user_stories do
        resources :user_story_acceptance_criterions
      end
    end
  end

  resources :locals
  resources :functions
  resources :abilities
end

app/models/ability.rb
class Ability < ApplicationRecord

  def self.available
    Ability.all
  end
  # Relacionamentos
  belongs_to :project, foreign_key: "scope",class_name: 'Project'
end

app/models/function.rb
class Function < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  def self.available_for_user user
    Language.all - user.languages 
  end
end

app/models/local.rb
class Local < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  def percentage_completed
    # Calculo ainda será implmentado
    rand(1...100)
  end

  # Projetos em aberto
  def self.available
    Project.all
  end

  # Relacionamentos
  has_many :function_user_projects
  has_many :users, through: :function_user_projects
  has_many :functions, through: :function_user_projects
  belongs_to :local
end

app/models/release.rb
class Release < ApplicationRecord

  def self.from_project project
    Release.where project: project
  end
  
  # Relacionamentos
  belongs_to :project
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :project
  belongs_to :release
end

app/models/task.rb
class Task < ApplicationRecord

  # Relacionamentos
  belongs_to :sprint
  belongs_to :user_story
end

app/models/task_requirement.rb
class TaskRequirement < ApplicationRecord
  belongs_to :task
  belongs_to :ability
end

app/models/theme.rb
class Theme < ApplicationRecord
  # Relacionamentos
  belongs_to :project
  has_many :user_stories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Foto
  mount_uploader :avatar, AvatarUploader

  # Permissão de acesso ao sistema apenas quando administrador validar
  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  # Relacionamentos
  belongs_to :local
  has_many :user_languages
  has_many :languages, through: :user_languages
  has_many :function_user_projects
  has_many :projects, through: :function_user_projects
  has_many :functions, through: :function_user_projects

  accepts_nested_attributes_for :local, reject_if: :all_blank, allow_destroy: true
end

app/models/user_ability.rb
class UserAbility < ApplicationRecord
  belongs_to :user
  belongs_to :ability
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :user
end

app/models/user_story.rb
class UserStory < ApplicationRecord

  # Relacionamentos
  has_many :user_story_acceptance_criterions
  belongs_to :theme
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.where(project: @project)
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
    @user_stories = @theme.user_stories
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)
    @theme.project = @project
    respond_to do |format|
      if @theme.save
        format.html { redirect_to [@project,@theme], notice: 'Tema criado com sucesso.' }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to [@project,@theme], notice: 'Tema foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to project_themes_path(@project), notice: 'Tema foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :project_id)
    end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/themes/_form.html.erb
<div class="ui form">
  <h4 class="ui dividing header">Informações</h4>
  <%= form_for([@project, theme]) do |f| %>
    <% if theme.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

        <ul>
        <% theme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="actions">
      <%= f.submit class:'ui teal button' %>
    </div>
  <% end %>
</div>

app/views/themes/edit.html.erb
<h1>Editar Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Detalhes', [@project,@theme], class: 'ui button' %>
<%= link_to 'Voltar', project_path(@project), class: 'ui button' %>

app/views/themes/index.html.erb
<h1 class="ui header" >Temas</h1>

<table class='ui orange table'>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.name %></td>
        <td><%= link_to 'Detalhes', [@project, theme], class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Editar', edit_project_theme_path(@project, theme), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Add User Story', new_project_theme_user_story_path(@project, theme), class: 'ui tiny green basic button' %></td>
        <td><%= link_to 'Excluir', [@project, theme], method: :delete, data: { confirm: 'Você tem certeza disso?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo tema', new_project_theme_path(@project), class: 'ui teal button' %>
<%= link_to 'Voltar', project_path(@project), class: 'ui button' %>

app/views/themes/new.html.erb
<h1>Novo Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Voltar', project_path(@project), class: 'ui button' %>

app/views/themes/show.html.erb
<div class='ui padded center aligned teal segment show'>
    <p>
    <strong>Nome:</strong>
    <%= @theme.name %>
  </p>

    <p>
    <strong>Projeto:</strong>
    <%= @theme.project.name %>
  </p>

  <%= link_to 'Editar', edit_project_theme_path(@project,@theme), class: 'ui button' %>
  <%= link_to 'Voltar', project_themes_path(@project), class: 'ui button' %>
</div>

<%= render 'user_stories/index' %>