config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index', to: 'dashboard#index', as: :dashboard_index
  get 'dashboard/normal', to: 'dashboard#normal', as: :dashboard_normal
  get 'get/project', to: 'projects#select', as: :selection_project

  post 'projects/create_repos' => 'projects#create_repos'

  get 'repository/index', to: 'repository#index', as: :repository_index
  get 'repository/branch', to: 'repository#branch', as: :repository_branch

  root to: 'dashboard#index'
  resources :languages
  resources :task_requirements
  resources :user_tasks
  resources :user_abilities
  resources :user_languages

  # Rotas devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved
  scope "/administrador" do
    resources :users
  end

  resources :projects do
    resources :function_user_projects
    resources :releases
    resources :sprints do
      resources :user_stories do # Recurso carregado duas vezes para facilitar no controler
        resources :tasks
      end
    end

    resources :themes do
      resources :user_stories do
        resources :user_story_acceptance_criterions
      end
    end
  end

  resources :locals
  resources :functions
  resources :abilities
end

app/models/ability.rb
class Ability < ApplicationRecord

  def self.available
    Ability.all
  end
  # Relacionamentos
  belongs_to :project, foreign_key: "scope",class_name: 'Project'
end

app/models/function.rb
class Function < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  def self.available_for_user user
    Language.all - user.languages 
  end
end

app/models/local.rb
class Local < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  def percentage_completed
    # Calculo ainda será implmentado
    rand(1...100)
  end

  # Projetos em aberto
  def self.available
    Project.all
  end

  # Relacionamentos
  has_many :function_user_projects
  has_many :users, through: :function_user_projects
  has_many :functions, through: :function_user_projects
  belongs_to :local
end

app/models/release.rb
class Release < ApplicationRecord

  def self.from_project project
    Release.where project: project
  end
  
  # Relacionamentos
  belongs_to :project
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :project
  belongs_to :release
end

app/models/task.rb
class Task < ApplicationRecord

  # Relacionamentos
  belongs_to :sprint
  belongs_to :user_story
end

app/models/task_requirement.rb
class TaskRequirement < ApplicationRecord
  belongs_to :task
  belongs_to :ability
end

app/models/theme.rb
class Theme < ApplicationRecord
  # Relacionamentos
  belongs_to :project
  has_many :user_stories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Foto
  mount_uploader :avatar, AvatarUploader

  # Permissão de acesso ao sistema apenas quando administrador validar
  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  # Relacionamentos
  belongs_to :local
  has_many :user_languages
  has_many :languages, through: :user_languages
  has_many :function_user_projects
  has_many :projects, through: :function_user_projects
  has_many :functions, through: :function_user_projects

  accepts_nested_attributes_for :local, reject_if: :all_blank, allow_destroy: true
end

app/models/user_ability.rb
class UserAbility < ApplicationRecord
  belongs_to :user
  belongs_to :ability
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :user
end

app/models/user_story.rb
class UserStory < ApplicationRecord

  # Relacionamentos
  has_many :user_story_acceptance_criterions
  belongs_to :theme
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  def select
      @projects = current_user.projects
      session[:project] = params['project_id'] if params['project_id']
  end
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @function_user_project = FunctionUserProject.new
  end

  # GET /projects/new
  def new
    @project = Project.new

  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json

  def create
    @project = Project.new(project_params)
    x = params[:opcao_privado] == "true"? true : false
    #funcao que cria repositorio no git
    @client.create_repository(@project.name, options = {"description": params[:description],
                    "homepage": params[:site],
                    "private": x,
                    "has_issues": params[:opc_issues],
                    "has_projects": params[:opc_project],
                    "has_wiki": params[:opc_wiki]})

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    #funcao que deleta repositorio do git
    @client.delete_repository(current_user.usernamegit+'/'+@project.name)

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_client
      @client = Octokit::Client.new(:login => current_user.usernamegit, :password => current_user.passwordgit)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :size, :start_date, :end_date, :local_id)
    end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<div class="ui form">
  <h4 class="ui dividing header">Informações</h4>
  <%= form_for(project) do |f| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :size, id: 'project_label_size' %>
        <%= f.range_field :size, :in => 0..10000, :step => '.1' %>
      </div>

        <div class="field">
          <%= f.label :start_date %>
          <%= f.date_select :start_date %>
        </div>

      <div class="field">
        <%= f.label :end_date %>
        <%= f.date_select :end_date, {:class => "input-mini"} %>
      </div>

      <div class="field">
        <%= f.label :local_id %>
        <%= f.collection_select(:local_id, Local.all, :id, :name, {:prompt=>true}, {:class=>'ui search dropdown'}) %>
      </div>

      <div>
        <%= label_tag 'Deseja criar repositório?' -%>
        <input type="checkbox" id="teste">
      </div>

      <div id="create_repos">
        <%= form_tag(projects_create_repos_path) do -%>
        
        <div class="field">
          <%= label_tag 'Web Site:' -%>
          <%= text_field_tag 'site', '', size: 30-%>
        </div>
        
        <div class="field">
          <%= label_tag 'Descrição:' -%>
          <%= text_field_tag 'description', '', size: 60-%>
        </div>
        
        <div class="field">
          <%= label_tag 'Privado:' -%>
          <%= radio_button_tag( 'opc_private', 'true')-%>
          <%= label_tag 'Sim' -%>
          <%= radio_button_tag( 'opc_private', 'false')-%>
          <%= label_tag 'Não' -%>
        </div>
        
        <div class="field">
          <%= label_tag 'Issues:' -%>
          <%= radio_button_tag( 'opc_issues', 'true')-%>
          <%= label_tag 'Sim' -%>
          <%= radio_button_tag( 'opc_issues', 'false')-%>
          <%= label_tag 'Não' -%>
        </div>
        
        <div class="field">
          <%= label_tag 'Projetos:' -%>
          <%= radio_button_tag( 'opc_project', 'true')-%>
          <%= label_tag 'Sim' -%>
          <%= radio_button_tag( 'opc_project', 'false')-%>
          <%= label_tag 'Não' -%>
        </div>
        
        <div class="field">
          <%= label_tag 'Wiki:' -%>
          <%= radio_button_tag( 'opc_wiki', 'true')-%>
          <%= label_tag 'Sim' -%>
          <%= radio_button_tag( 'opc_wiki', 'false')-%>
          <%= label_tag 'Não' -%>   
        </div>
        
      </div>

      <div class="actions">
      <%= f.submit class:'ui teal button' %>
    </div>
    <% end -%>
  <% end %>
</div>

<script type="text/javascript">
  $(".form").change(function() {
    input = $("#project_size").val();
    label = $("#project_label_size");
    label.text("Tamanho " + input);
    console.log("Current Value = " + input);
  })

    document.getElementById("create_repos").style.display="none";
  $("#teste").click(function(){
    console.log($("#teste").val());
    if($("#teste").val() === "on"){
      document.getElementById("create_repos").style.display="inline";
      $("#teste").val("off");
    }
    else{
      document.getElementById("create_repos").style.display="none";
      $("#teste").val("on");
    }
  });

</script>

app/views/projects/edit.html.erb
<h1>Editar Projeto</h1>

<%= render 'form', project: @project %>

<%= link_to 'Detalhes', @project, class: 'ui button' %>
<%= link_to 'Voltar', projects_path, class: 'ui button' %>

app/views/projects/index.html.erb
<h1 class="ui header" >Projects</h1>

<table class='ui orange table'>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tamanho</th>
      <th>Data de ínicio</th>
      <th>Data de termino</th>
      <th>Localidade</th>
      <th>Porcentagem completada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.size %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.local.name %></td>
        <td>
          <div class="ui indicating progress" data-percent="<%= project.percentage_completed %>">
              <div class="bar" style="transition-duration: 300ms; width: <%= project.percentage_completed %>%;"></div>
              <div class="label">Completado</div>
          </div>
        </td>
        <td><%= link_to 'Detalhes', project, class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Editar', edit_project_path(project), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Excluir', project, method: :delete, data: { confirm: 'Você tem certeza disso?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Project', new_project_path, class: 'ui teal button' %>

app/views/projects/new.html.erb
<h1>Novo Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Voltar', projects_path, class: 'ui button' %>

app/views/projects/select.html.erb
<table class="ui teal table">
   <thead>
     <tr>
       <th>Projeto</th>
       <th>Ínicio</th>
       <th>Fim</th>
       <th>Progresso</th>
       <th colspan="4"></th>
     </tr>
   </thead>

   <tbody>
     <% @projects.each do |project| %>
       <tr>
         <td><%= project.name %></td>
         <td><%= l(project.start_date) %></td>
         <td><%= l project.end_date %></td>
         <td>
           <div class="ui indicating progress" data-percent="<%= project.percentage_completed %>">
               <div class="bar" style="transition-duration: 300ms; width: <%= project.percentage_completed %>%;"></div>
               <div class="label">Completado</div>
           </div>
         </td>
         <td class="right aligned" ><%= link_to 'Escolher projeto', selection_project_path(project_id: project.id), class: 'ui tiny positive button' %></td>
         <td><%# link_to 'Editar', edit_report_path(report), class: 'ui tiny blue basic button' %></td>
         <td><p><%# link_to 'Ver imagens', images_for_report_index_path(devic: report.id), class: 'ui tiny green basic button' %></p></td>
         <td><%# link_to 'Excluir', report, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui tiny red basic button' %></td>
       </tr>
     <% end %>
   </tbody>
</table>

app/views/projects/show.html.erb
<div class='ui padded center aligned teal segment show'>

<h4>Dados do Projeto</h4>
    <p>
    <strong>Nome:</strong>
    <%= @project.name %>
  </p>

    <p>
    <strong>Tamanho do projeto:</strong>
    <%= @project.size %>
  </p>

    <p>
    <strong>Data de ínicio:</strong>
    <%= l @project.start_date %>
  </p>

    <p>
    <strong>Data de termino:</strong>
    <%= l @project.end_date %>
  </p>

    <p>
    <strong>Localidade:</strong>
    <%= @project.local.name %>
  </p>

    <%= link_to 'Editar', edit_project_path(@project), class: 'ui button' %>
    <%= link_to 'Voltar', projects_path, class: 'ui button' %>
</div>

<div class='ui padded center aligned blue segment show'>
  <%= link_to 'Adicionar membro ao projeto', new_project_function_user_project_path(@project,@function_user_project),class: 'ui positive button'%>
  <%= link_to 'Gerenciar Sprints', project_sprints_path(@project),class: 'ui positive button'%>
  <%= link_to 'Gerenciar Releases', project_releases_path(@project),class: 'ui positive button'%>
  <%= link_to 'Gerenciar Temas', project_themes_path(@project),class: 'ui positive button'%>
  <%= link_to 'Visualizar Repositório', repository_index_path(project_receive: @project),class: 'ui positive button'%>
</div>

<h1 class"ui header">Membros do projeto</h1>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Função</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project.function_user_projects.each do |member| %>
      <tr>
        <td><%= member.user.name %></td>
        <td><%= member.function.name %></td>
        <td><%= link_to 'Editar', edit_project_function_user_project_path(@project,member, edit: :true), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Excluir', project_function_user_project_path(@project,member), method: :delete, data: { confirm: 'Você tem certeza que deseja excluir o membro desse projeto?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
if (@verif_repo){
  document.getElementById("exibe_repos").style.display="none";
}
else{
  document.getElementById("exibe_repos").style.display="inline";
}

</script>

app/views/projects/show_repository_project.html.erb
<h3 class"ui header">Dados Gerais</h3>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Home Page</th>
      <th>Private</th>
      <th>Issues</th>
      <th>Projetos</th>
      <th>Wiki</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @var.name %></td>
        <td><%= @var.description %></td>
        <td><%= @var.homepage %></td>
        <td><%= @var.private %></td>
        <td><%= @var.has_issues %></td>
        <td><%= @var.has_projects %></td>
        <td><%= @var.has_wiki %></td>
      </tr>
  </tbody>
</table>

<h3 class"ui header">Branches</h3>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Nome</th>
      <th>SHA</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @bra.each do |branches| %>
      <tr>
        <td><%= branches.name %></td>
        <td><%= branches.commit.sha %></td>
        <td><%= branches.commit.url %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<div class="field">
  <%= label_tag 'Selecione Branch' %>
  <%= select_tag 'branches', options_from_collection_for_select(@bra, "name", "name"), prompt: "Selecione a Branch" %>
</div>

<h3 class"ui header">Branch</h3>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Nome</th>
      <th>SHA</th>
      <th>Usuário last update</th>
      <th>Nome last update</th>
      <th>Data/hora laste update</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%=@unibra.name %></td>
        <td><%=@unibra.commit.sha %></td>
        <td><%=@unibra.commit.author.login %></td>
        <td><%=@unibra.commit.commit.author.name %></td>
        <td><%=@unibra.commit.commit.author.date %></td>
      </tr>
  </tbody>
</table>

<h3 class"ui header">Lista de Commits</h3>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%#= @com.commit.author.name %></td>
        <td><%#= @com.commit.author.date %></td>
        <td><%#= @com.commit.message %></td>
        <td><%#= @com.author.login %></td>
        <td><%#= @com.committer.login %></td>
      </tr>
  </tbody>
</table>